---
- name: Init Docker Swarm on node 1
  community.docker.docker_swarm:
    advertise_addr: hostvars[ groups['swarm-managers'] | first ]['ansible_host']:4567
    state: present

- name: Get the Manager join-token
  shell: docker swarm join-token --quiet manager
  register: manager_token

- name: Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token