version: '3.8'

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=vcc-test
      - POSTGRES_PASSWORD=vcc-test
    ports:
      - '5432:5432'
    volumes: 
      - "/data/postgresql:/var/lib/postgresql/data"
      - "/opt/keycloak.sql:/docker-entrypoint-initdb.d/keycloak.sql"
      - "/opt/nextcloud.sql:/docker-entrypoint-initdb.d/nextcloud.sql"
    # networks:
    #   - swarm_net

volumes:
  db:
    driver: local

