version: "3.8"

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=vcc-test
      - POSTGRES_PASSWORD=vcc-test
    ports:
      - "5432:5432"
    volumes:
      - "/data/postgresql:/var/lib/postgresql/data"
      - "/opt/keycloak.sql:/docker-entrypoint-initdb.d/keycloak.sql"
      - "/opt/nextcloud.sql:/docker-entrypoint-initdb.d/nextcloud.sql"
    networks:
      # - overlay_swarm_net
      - traefik_public
      

volumes:
  db:
    driver: local

networks:

  # overlay_swarm_net:
  #   name: overlay_swarm_net
  #   external: true
  traefik_public:
    driver: overlay
    name: traefik_public
    attachable: true

  # overlay_swarm_net:
  #   name: overlay_swarm_net
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: "192.168.60.0/24"
