---
- name: Create /data/docker-registry
  ansible.builtin.file:
    path: "{{ registry }}"
    state: directory

- name: Copy the registry stack file
  ansible.builtin.template:
    src: registry.yml
    dest: /opt/registry.yml

- name: Copy the registry config file
  ansible.builtin.template:
    src: registry.config.yml
    dest: "{{ registry }}/registry.config.yml"

- name: Install apache2-utils for htpasswd
  ansible.builtin.apt:
    name: apache2-utils

- name: Install passlib with pip
  ansible.builtin.pip:
    name: passlib
    state: present
    executable: pip3
  become: true

- name: Create registry configuration
  community.docker.docker_config:
    name: registry_configuration
    state: present
    data_src: "{{ registry }}/registry.config.yml"

- name: Create htpasswd file
  ansible.builtin.file:
    path: "{{ registry_htpasswd_file }}"
    state: touch
    mode: '0755'
   
- name: Insert passwords in htpasswd file
  community.general.htpasswd:
    path: "{{ registry_htpasswd_file }}"
    name: "{{ REGISTRY_USER }}"
    password: "{{ REGISTRY_PASSWORD}}"
    crypt_scheme: bcrypt
    mode: '0777'

- name: Deploy registry stack from a compose file
  community.docker.docker_stack:
    state: present
    name: registry
    compose:
    - /opt/registry.yml