---
- name: Copy the  stack file
  ansible.builtin.template:
    src: keycloak_stack.yml
    dest: /opt/keycloak_stack.yml

- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: keycloak
    compose:
      - /opt/keycloak_stack.yml
    with_registry_auth: true
