---
- name: Common part of the playbook for both nodes
  hosts: all
  become: true
  vars_files: 
    - secrets.yml
  roles:
    - update
    - nfs
    - docker
    - logging_common
    - docker_swarm

- name: Registry Services
  hosts: node1
  vars_files: 
    - secrets.yml
  become: true
  roles:
    - registry
    - registry_cache

- name: Registry Login
  hosts: all
  vars_files: 
    - secrets.yml
  become: true
  roles:
    - registry_login
    
- name: Database Services
  hosts: node1
  vars_files: 
    - secrets.yml
  become: true
  roles:
    - database

- name: Keycloak Services
  hosts: node1
  vars_files: 
    - secrets.yml
  become: true
  roles:
    - keycloak

- name: Nextcloud Services
  hosts: node1
  vars_files: 
    - secrets.yml
  become: true
  roles:
    - nextcloud

- name: Traefik Services
  hosts: node1
  vars_files: 
    - secrets.yml
  become: true
  roles:
    - traefik

- name: Logging services
  hosts: node1
  vars_files: 
    - secrets.yml
  become: true
  roles:
    - logging

- name: Grafana services
  hosts: node1
  vars_files: 
    - secrets.yml
  become: true
  roles:
    - monitoring
