---
- name: Create or modify docker daemon
  ansible.builtin.copy:
    dest: "{{ daemon_file }}"
    content: |
      {{ daemon_content }}
    mode: '0777'

- name: Restart Docker service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: docker


- name: "Render fluent-bit.conf file using variables"
  ansible.builtin.template:
    src: "fluentbit.j2"
    dest: "/opt/fluent-bit.conf"
    mode: '0777'

- name: "Copy fluentbit parsers"
  ansible.builtin.template:
    src: "parser.conf"
    dest: "/opt/parser.conf"
    mode: '0777'

- name: Copy the sql file for keycloak stack file
  ansible.builtin.template:
    src: keycloak.sql
    dest: /opt/keycloak.sql
    mode: "0644"

- name: Copy the sql file for nextcloud  file
  ansible.builtin.template:
    src: nextcloud.sql
    dest: /opt/nextcloud.sql
    mode: "0644"

