version: '3.8'
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - /data/postgresql:/var/lib/postgresql/data
volumes:
  db:
    driver: local

