---
- name: Copy the database stack file
  ansible.builtin.template:
    src: postgres.yml
    dest: /opt/postgres.yml
    mode: "0644"

- name: Delete /data/postgres directory to store nextcloud data.
  ansible.builtin.file:
    path: /data/postgresql
    state: absent

- name: Create /data/postgres directory to store SQL data.
  ansible.builtin.file:
    path: /data/postgresql
    state: directory

- name: Deploy gitea stack from a compose file
  community.docker.docker_stack:
    state: present
    name: postgres
    compose:
    - /opt/postgres.yml
    with_registry_auth: true
