---
- name: Delete nextcloud image 
  community.docker.docker_image:
    build:
      path: "/opt/nextcloud/container/"
      nocache: true
    name: "{{ registry_url }}:{{ registry_port }}/nextcloud"
    source: build
    state: absent
    force_absent: true

- name: Build an image and push it to a private repo
  community.docker.docker_image:
    build:
      path: "{{ shared_volumes }}/nextcloud/container/"
      nocache: true
    name: "{{ registry_url }}:{{ registry_port }}/nextcloud"
    push: true
    source: build
    debug: true



- name: Copy the  stack file
  ansible.builtin.template:
    src: nextcloud_stack.yml
    dest: /opt/nextcloud_stack.yml
    mode: "0644"

- name: Delete /data/nextcloud directory to store nextcloud data.
  ansible.builtin.file:
    path: /data/nextcloud
    state: absent

- name: Create /data/nextcloud directory to store nextcloud data.
  ansible.builtin.file:
    path: /data/nextcloud
    state: directory
    mode: "0755"

- name: Copy nextcloud-integrator folder to node
  ansible.builtin.copy:
    src: container/
    dest: /opt/nextcloud_integrator
    mode: 0644
    
- name: Build and push container
  community.docker.docker_image:
    build:
      path: /opt/nextcloud_integrator/
    name: 127.0.0.1:5000/nextcloud-keycloak-integrator
    tag: latest
    push: true
    source: build

- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: nextcloud
    compose:
      - /opt/nextcloud_stack.yml
    with_registry_auth: true
