---
- name: Erase nextcloud image in order to update entrypoint
  community.docker.docker_image:
    build:
      path: "/opt/nextcloud/"
      nocache: true
    name: "127.0.0.1:5000/nextcloud"
    source: build
    state: absent
    force_absent: true

- name: copy nextcloud folder to node
  ansible.builtin.copy:
    src: nextcloud/
    dest: /opt/nextcloud/
    mode: 0777

- name: Create directories needed for logging 
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items:
    - "/data/logs/nextcloud"
    - "/data/lock"

- name: Create file needed for nextcloud logging
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: '0777'
  with_items:
    - "/data/logs/nextcloud/nextcloud.log"


- name: Build and push nextcloud container
  community.docker.docker_image:
    build:
      path: /opt/nextcloud/container/
    name: 127.0.0.1:5000/nextcloud
    tag: latest
    push: true
    source: build

- name: Copy the  stack file
  ansible.builtin.template:
    src: nextcloud_stack.yml
    dest: /opt/nextcloud_stack.yml
    mode: "0644"

- name: Delete /data/nextcloud directory to store nextcloud data.
  ansible.builtin.file:
    path: /data/nextcloud
    state: absent

- name: Create /data/nextcloud directory to store nextcloud data.
  ansible.builtin.file:
    path: /data/nextcloud
    state: directory
    mode: "0755"

- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: nextcloud
    compose:
      - /opt/nextcloud_stack.yml
    with_registry_auth: true
