---
- name: Install NFS server on node1
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  when: inventory_hostname is in groups['nfs-servers']

- name: Create data directory on node1
  ansible.builtin.file:
    path: /data
    state: directory
  when: inventory_hostname is in groups['nfs-servers']

- name: Template NFS /etc/exports
  ansible.builtin.template:
    src: exports
    dest: /etc/exports
  notify:
  - Restart NFS server
  when: inventory_hostname is in groups['nfs-servers']

- name: Restart NFS service on node1
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
  when: inventory_hostname is in groups['nfs-servers']


- name: Install NFS client on node2
  ansible.builtin.apt:
    name: nfs-common
    state: present
  when: inventory_hostname is in groups['nfs-clients']


- name: "Create NFS mount directory {{ nfs_share_path }}"
  ansible.builtin.file:
    path: "{{ nfs_share_path }}"
    state: directory
  when: inventory_hostname is in groups['nfs-clients']

- name: Mount NFS
  ansible.posix.mount:
    src: "{{ hostvars[ groups['nfs-servers'] | first ]['ansible_host'] }}:{{ nfs_share_path }}"
    path: "{{ nfs_share_path }}"
    opts: rw
    fstype: nfs
    state: mounted
  when: inventory_hostname is in groups['nfs-clients']
