---
version: 0.1
name: registry_cache_configuration
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
    filesystem:
      rootdirectory: /var/lib/registry-cache
http:
  addr: :5001
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: basic-realm
    path: /data/docker-registry/htpasswd
mirrors:
  - http://127.0.0.1:5001