version: 0.1

storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true

auth:
  htpasswd:
    realm: Docker registry
    path: /etc/registry.htpasswd

http:
  addr: :5000
  debug:
    addr: :5001

prometheus:
  enabled: true
