version: "3.8"
services:
  registry:
    image: distribution/distribution:2.8.1
    #restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 5001:5001
      #- 127.0.0.1:5001:5001
    volumes:
      - /data/docker-registry-cache:/var/lib/registry-cache
      - /data/docker-registry-cache/registry-cache.config.yml:/etc/docker/registry-cache/config.yml:ro
      #- /data/docker-registry-cache/registry-cache.htpasswd:/etc/registry-cache.htpasswd:ro
    