---
- name: Create or modify docker daemon
  ansible.builtin.copy:
    dest: "{{ daemon_file }}"
    content: |
      {{ daemon_content }}
    mode: '0777'

- name: Restart Docker service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: docker

- name: Copy the prometheus directory
  ansible.builtin.copy:
    src: prometheus/
    dest: /data/prometheus
    mode: "0644"

- name: Copy the grafana directory
  ansible.builtin.copy:
    src: grafana/
    dest: /data/grafana
    mode: "0644"

- name: Change ownership of prometheus to nobody for persisting data.
  file:
    path: /data/prometheus
    owner: nobody
    group: nogroup
    recurse: yes
    state: directory

- name: Copy the fluentbit configuration  file
  ansible.builtin.template:
    src: fluent-bit.conf
    dest: /opt/fluent-bit.conf
    mode: "0644"

- name: Copy the loki configuration file
  ansible.builtin.copy:
    src: loki/loki.conf
    dest: /opt/loki.conf
    mode: "0644"

- name: Copy the backend stack file
  ansible.builtin.template:
    src: logging.yml
    dest: /opt/logging.yml
    mode: "0644"

- name: Deploy backend stack from a compose file
  community.docker.docker_stack:
    state: present
    name: backend
    compose:
      - /opt/logging.yml
    with_registry_auth: true
