---
# - name: "Render fluent-bit.conf file using variables"
#   ansible.builtin.template:
#     src: "fluentbit.j2"
#     dest: "/opt/fluent-bit.conf"
#     mode: '0777'

- name: Create directories if they do not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items:
    - "/data/logs/traefik"
    - "/data/logs/nextcloud"
    - "/data/logs/keycloak"
    - "/data/loki"
    - "/data/prometheus"
    - "/data/grafana"

- name: Copy the prometheus directory
  ansible.builtin.copy:
    src: prometheus/
    dest: /data/prometheus
    mode: "0644"

- name: Change ownership of prometheus to nobody for persisting data.
  file:
    path: /data/prometheus
    owner: nobody
    group: nogroup
    recurse: yes
    state: directory

- name: Copy the loki configuration file
  ansible.builtin.copy:
    src: loki/loki.conf
    dest: /opt/loki.conf
    mode: "0644"

- name: Copy the backend stack file
  ansible.builtin.template:
    src: logging.yml
    dest: /opt/logging.yml
    mode: "0644"

- name: Deploy backend stack from a compose file
  community.docker.docker_stack:
    state: present
    name: backend
    compose:
      - /opt/logging.yml
    with_registry_auth: true
