version: "3.8"
configs:
  loki_config:
    file: /opt/loki.conf

volumes:
  data: {}

services:
  loki:
    image: grafana/loki:2.7.1
    configs:
      - source: loki_config
        target: /etc/loki/loki-config.yaml
    volumes:
      - /data/loki:/loki
    networks:
      - traefik_public
    deploy:
      placement:
        constraints:
          - node.role == manager

  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.0.6
    deploy:
      mode: global
    environment:
      LOKI_URL: http://loki:3100/loki/api/v1/push
    networks:
      - traefik_public
    volumes:
      - /opt/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /opt/parser.conf:/parser.conf
      - /data/logs/keycloak/keycloak.log:/keycloak.log
      - /data/logs/nextcloud/nextcloud.log:/nextcloud.log
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /sys/fs/cgroup/:/sys/fs/cgroup/
      - /var/log/journal:/run/log/journal:ro
      - /var/run/systemd/journal:/var/run/systemd/journal:ro
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs:ro
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:v2.40.6
    user: root
    network_mode: "host"   
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
    networks:
      - traefik_public
    volumes:
      - /data/prometheus:/app.cfg
      - /data/prometheus:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
    command: >-
      --config.file=/app.cfg/prometheus.yml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=7d
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles

  
  node-exporter:
    image: prom/node-exporter:v1.3.1
    deploy:
      mode: global
    restart: always
    networks:
      - traefik_public
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'

#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor-arm64:0.99-porterdavid
#    command: ["start", "--privileged"]
#    networks:
#      - traefik_public
#    privileged: true
#    deploy:
#      mode: global
#      labels:
#        prometheus-job: cadvisor
#    devices:
#      - /dev/kmsg:/dev/kmsg
#    volumes:
#        - /:/rootfs:ro
#        - /var/run:/var/run:ro
#        - /sys:/sys:ro
#        - /var/lib/docker/:/var/lib/docker:ro
#        - /dev/disk/:/dev/disk:ro
#        - /etc/machine-id:/etc/machine-id:ro
#        - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
#        - /dev/kmsg:/dev/kmsg:rw
        

networks:
  traefik_public:
    external: true