version: "3"

networks:
  overlay_swarm_net:
    name: overlay_swarm_net
    external: true

  traefik_public:
    external: true

services:
  nextcloud:
    image: 127.0.0.1:5000/nextcloud
    hostname: nextcloud
    deploy:
      mode: replicated
      replicas: 5
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.nextcloud.entrypoints=websecure"
        - "traefik.http.routers.nextcloud.rule=Host(`cloud.localdomain`)"
        - "traefik.http.routers.nextcloud.service=nextcloud_service"
        - "traefik.http.routers.nextcloud.tls=true"
        - "traefik.http.routers.nextcloud.middlewares=nextcloud_proto"
        - "traefik.http.services.nextcloud_service.loadbalancer.server.port=80"
        - "traefik.http.middlewares.nextcloud_proto.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.services.nextcloud_service.loadbalancer.sticky=true"
        - "traefik.http.services.nextcloud_service.loadbalancer.sticky.cookie.name=StickyCookie"
        - "traefik.http.services.nextcloud_service.loadbalancer.sticky.cookie.secure=true"

    extra_hosts:
      - "auth.localdomain:192.168.50.10"
    volumes:
      - /data/nextcloud:/var/www/html
      - /data/logs/nextcloud/nextcloud.log:/nextcloud.log
      - /data/lock:/var/lock
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.localdomain
      - OIDC_CLIENT_ID=nextcloud
      - OIDC_PROVIDER_URL=https://auth.localdomain/realms/vcc/
      - OIDC_LOGOUT_URL=https://cloud.localdomain/apps/oidc_login/oidc
      - OIDC_CLIENT_SECRET=nLMC8I6MLnfTnAeK23fFWYNiYpSrERmn
      


    networks:
      # overlay_swarm_net:
      traefik_public:

    depends_on:
      - postgres_db
      - keycloak_keycloak
