version: "3"
## TODO : Extra hosts

networks:
  overlay_swarm_net:
    name: overlay_swarm_net
    external: true

  traefik_public:
    external: true

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:23.0-apache
    hostname: nextcloud
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.nextcloud.entrypoints=websecure"
        - "traefik.http.routers.nextcloud.rule=Host(`cloud.localdomain`)"
        - "traefik.http.routers.nextcloud.service=nextcloud_service"
        - "traefik.http.routers.nextcloud.tls=true"
        - "traefik.http.routers.nextcloud.middlewares=nextcloud_proto"
        - "traefik.http.services.nextcloud_service.loadbalancer.server.port=80"
        - "traefik.http.middlewares.nextcloud_proto.headers.customrequestheaders.X-Forwarded-Proto=https"
    volumes:
      - /data/nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.localdomain

    extra_hosts:
      - "auth.localdomain:192.168.50.5"

    networks:
      overlay_swarm_net:
        ipv4_address: 192.168.50.7
      traefik_public:

    depends_on:
      - db

  nextcloud-keycloak-integrator:
    image: 127.0.0.1:5000/nextcloud-keycloak-integrator
    restart: on-failure
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud_nextcloud
      - KEYCLOAK_CONTAINER_NAME=keycloak_keycloak
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - SAMPLE_USER_PASSWORD=itsdifficult
      - OIDC_CLIENT_ID=nextcloud
      - OIDC_PROVIDER_URL=https://auth.localdomain:8080/realms/vcc
      - OIDC_LOGOUT_URL=https://cloud.localdomain/apps/oidc_login/oidc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - keycloak
      - nextcloud
    networks:
      - overlay_swarm_net
      - traefik_public

    extra_hosts:
      - "auth.localdomain:192.168.50.5"
