version: '3'

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:23.0-apache
    hostname: 192.168.50.10
    ports:
      - '80:80'
    deploy:
      replicas: 1
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.localdomain`)"
      - "traefik.http.routers.nextcloud.entrypoints=web-secure"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

    volumes:
      - /data/nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=192.168.50.10
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.50.10
    networks:
      - my_overlay_network
    depends_on:
      - db
  
  nextcloud-keycloak-integrator:
      image: 127.0.0.1:5000/nextcloud-keycloak-integrator
      restart: on-failure
      network_mode: host
      environment:
        - NEXTCLOUD_CONTAINER_NAME=nextcloud_nextcloud
        - KEYCLOAK_CONTAINER_NAME=keycloak_keycloak
        - KEYCLOAK_ADMIN_USER=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - SAMPLE_USER_PASSWORD=itsdifficult
        - OIDC_CLIENT_ID=nextcloud
        - OIDC_PROVIDER_URL=http://192.168.50.10:8080/realms/vcc
        - OIDC_LOGOUT_URL=http://192.168.50.10/apps/oidc_login/oidc
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

      depends_on:
        - keycloak
        - nextcloud
      networks:
      - my_overlay_network

networks:
  my_overlay_network:
    driver: overlay
    name: my-overlay-network