---
- name: Init Docker Swarm on node 1
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ hostvars[groups['swarm-managers'] | first ]['ansible_host']}}:2375"
  register: result
  when: inventory_hostname is in groups['swarm-managers']

- name: Get join-token for worker nodes
  set_fact:
    join_token_worker: "{{ hostvars[groups['swarm-managers'][0]].result.swarm_facts.JoinTokens.Worker }}"

- name: Join workers
  community.docker.docker_swarm:
    state: join
    join_token: "{{ join_token_worker }}"
    advertise_addr: "{{ ansible_host }}"
    remote_addrs: "{{ hostvars[groups['swarm-managers'][0]].ansible_host }}"
  when: inventory_hostname in groups['swarm-workers']
