{
 "title": "Logs_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Keycloak ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Keycloak Logs Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate({job=\"keycloak-logs\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Keycloak Logs (Trace)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"keycloak-logs\"}"
    }
   ]
  },
  { "title": "System logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Node 1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"system-logs\", host=\"node1\"}"
    }
   ]
  },
  {
   "title": "Node 2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{host=\"node2\",job=\"system-logs\"}"
    }
   ]
  },
  { "title": "Docker logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Node 1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{host=\"node1\", job=\"docker-logs\"}"
    }
   ]
  },
  {
   "title": "Node 2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "{host=\"node2\", job=\"docker-logs\"}"
    }
   ]
  }
 ]
}