---
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker