---
- name: Update package lists
  ansible.builtin.apt:
    update_cache: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Add Docker key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present

- name: Install PIP
  ansible.builtin.apt:
    name: python3-pip
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker-cli
