version: '3'

services:
  reverse-proxy-https-init:
      image: 127.0.0.1:5000/alpine/openssl:3.14
      build: 
        context: /opt/sslgenerator/ssl-init
        dockerfile: Dockerfile
      environment: 
        SSL_CN: "*.local"
        SSL_O: "VCC"
        SSL_C: "IT"
        SSL_DAYS: 3650
      volumes:
        - /data/certs:/etc/ssl/traefik
        - /data/traefik:/etc/traefik/dynamic
      deploy:
        restart_policy:
          condition: none
        mode: replicated
        replicas: 1
        
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9.6
    # Enables the web UI and tells Traefik to listen to docker
    command: 
         # enable Web UI
      - --api.insecure=true
      - --metrics
      - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
      # set provider (Docker Swarm)
      - --providers.docker
      - --providers.docker.swarmMode=true
      # traefik http entrypoint port
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # redirect
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      # add x-forwaded-for
      - --entrypoints.web.forwardedHeaders.insecure=true
      # manually enable services exposed by traefik
      - --providers.docker.exposedByDefault=false
      # dynamic configuration files folder
      - --providers.file.directory=/etc/traefik/dynamic
      - --log.level=DEBUG
      # log
      - "--accesslog=true"
      - "--accesslog.filePath=/logs/access.log"

    ports:
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
      - 443:443
      - 80:80
    volumes:
      # So that Traefik can listen to the Docker even
      - /data/:/logs
      - /data/certs:/etc/ssl/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik:/etc/traefik/dynamic


    networks:
      - overlay_swarm_net
      - traefik_public
   
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  overlay_swarm_net:
    name: overlay_swarm_net
    external: true
  
  traefik_public:
    external: true