---
- name: Copy the traefik stack file
  ansible.builtin.template:
    src: traefik.yml
    dest: /opt/traefik.yml
    mode: "0644"

- name: Copy the ssl int docker file directory
  ansible.builtin.copy:
    src: ssl-init/
    dest: /opt/sslgenerator/ssl-init
    mode: "0644"
    
- name: Create /data/certs directory to store certificates.
  ansible.builtin.file:
    path: /data/certs
    state: directory
    mode: "0644"

- name: Create /data/traefik directory to store traefik data.
  ansible.builtin.file:
    path: /data/traefik
    state: directory
    mode: "0644"

- name: Build and push ssl init container
  community.docker.docker_image:
    build:
      path: /opt/sslgenerator/ssl-init/
    name: 127.0.0.1:5000/alpine/openssl:latest
    tag: latest
    push: true
    source: build

- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: traefik
    compose:
    - /opt/traefik.yml
    with_registry_auth: true