version: "3.8"

volumes:
  data: {}

networks:
  # overlay_swarm_net:
  #   name: overlay_swarm_net
  #   external: true

  traefik_public:
    external: true

services:

  grafana:
    depends_on:
      - loki
    image: grafana/grafana:8.5.0
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.rule=Host(`mon.localdomain`)"
        - "traefik.http.routers.grafana.service=grafana_service"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.routers.grafana.middlewares=grafana_proto"
        - "traefik.http.services.grafana_service.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.grafana_proto.headers.customrequestheaders.X-Forwarded-Proto=https"
      mode: replicated
      replicas: 1
    extra_hosts:
      - "auth.localdomain:192.168.50.10"
    environment:
      GF_SECURITY_ADMIN_USER: '{{ GF_SECURITY_ADMIN_USER }}'
      GF_SECURITY_ADMIN_PASSWORD: test
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_SCOPES: openid email profile
      GF_AUTH_GENERIC_OAUTH_NAME: "Keycloak"
      GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE: "true"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.localdomain/realms/vcc/protocol/openid-connect/userinfo"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.localdomain/realms/vcc/protocol/openid-connect/auth"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.localdomain/realms/vcc/protocol/openid-connect/token"    
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "grafana"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "nLMC8I6MLnfTnAeK23fFAWCiYpSrERdg"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(roles[*], 'Admin') && 'Admin' || contains(roles[*], 'Editor') && 'Editor' || 'Viewer'"
      GF_SERVER_DOMAIN: mon.localdomain
      GF_SERVER_ROOT_URL: https://mon.localdomain
    networks:
      # - overlay_swarm_net
      - traefik_public

    volumes:
      # - /data/grafana:/var/lib/grafana
      # - /data/grafana:/conf/provisioning/
      # - /data/grafana/dashboard_prov:/etc/grafana/provisioning/dashboards
      # - /data/grafana/dashboards:/var/lib/grafana/dashboards
      # - /data/grafana/dashboards:/usr/share/grafana/public/dashboards/
      - /data/grafana:/var/lib/grafana
      - /data/grafana/datasources:/etc/grafana/provisioning/datasources
      - /data/grafana/dashboard_prov:/etc/grafana/provisioning/dashboards
      - /data/grafana/dashboards:/var/lib/grafana/dashboards
 
